name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        os: [ubuntu-latest]
        crystal:
          - latest
        include:
          - experimental: true
            os: ubuntu-latest
            crystal: nightly
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal }}-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Install build deps
      run: |
        apk add --update --no-cache python3 cmake g++ make
        (cd "/usr/bin" && wget https://releases.bazel.build/5.3.0/release/bazel-5.3.0-linux-x86_64 && chmod +x bazel-5.3.0-linux-x86_64)
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Install Tensor Flow
      run: sh ./build_tensorflowlite.sh
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec -v --error-trace
      env:
        LD_LIBRARY_PATH: /usr/local/lib
