name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        os: [ubuntu-latest]
        crystal:
          - master-debian-11
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    container: 84codes/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v3
    - name: Install build deps
      run: |
        apt-get update && apt-get install -y gnupg wget curl apt-transport-https ca-certificates
        wget -q -O - https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/coral-edgetpu.gpg
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/coral-edgetpu.gpg] https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
        apt update && apt install -y build-essential cmake linux-headers-generic git python3 opencl-headers libopencv-core-dev clang-format-9 libedgetpu-dev libedgetpu1-std
    - name: Install dependencies
      run: shards install --ignore-crystal-version -v
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec -v --error-trace
      env:
        LD_LIBRARY_PATH: /usr/local/lib
